name: Push to main

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: "Generate diffs"
      run: |
        git config --global user.name 'Version Bot'
        git config --global user.email 'version-bot@users.noreply.github.com'
        curl --output generate-diffs.php https://raw.githubusercontent.com/laravel-upgrade-helper/laravel-diff-generator/main/generate-diffs.php
        php ./generate-diffs.php
        LATEST_VERSION=$(tail -n 1 tags.txt)
        LATEST_VERSION_ON_PROD=$(curl -s https://laravel-upgrade-helper.github.io/tags.txt | tail -n 1)
        if [[ git diff ./tags.txt ]]; then
          git add .
          git commit -m "[Version-Bot] Add Laravel Version"
          git push origin gh-pages
        else
          echo "No new version!"
        fi
